spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/flightApp
    username: flightApp
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: 743777217A25432A462D4A614E635266556A586E3272357538782F413F442847
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
server:
  port: 8088

bezkoder:
  openapi:
    dev-url: http://localhost:8088
    prod-url: https://localhost:8080

logging:
  level:
    org:
    springframework:
      security: DEBUG
      web: DEBUG
      data: DEBUG
      hibernate: DEBUG
      jpa: DEBUG
      sql: DEBUG
      jwt: DEBUG
      bezkoder: DEBUG
