version: '3.8'
services:
  flightApp-postgresql:
    image: postgres:14.2

    environment:
      - POSTGRES_USER=flightApp
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust

    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
